apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-appgke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-appgke
  template:
    metadata:
      labels:
        app: python-appgke
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: python-appgke
        image: gcr.io/icai2025/python-appgke:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000


